### DISCUSSION TITLE
New format of the filter states

### DISCUSSION THREAD

**Discussion by gogonzo** [insightsengineering/teal.slice#349] [General]
@shajoezhu @lcd2yyz after refactor of the filter panel we removed "natural language formatting" of the filter states and they are all now printed in a technical way. Output you see here is the same for `print(filter_states)`, `save(filter_states)` and for a `TealReporter` (used in tmc). There was a strong reason to change it as our classes were simply to complex and we needed to make some tradeoffs, and formatting was implemented in a way we shouldn't really release in the first time.
This "technical" print is fully repproducible and can be reused to restore filters - this is exact way in which we are going to store filters for bookmarking

| Before  | Now |
| ------------- | ------------- |
| <img alt="Skärmavbild 2023-06-19 kl  12 39 00" src="https://github.com/insightsengineering/teal.slice/assets/6959016/9a3ed510-f0dc-44af-8a1a-fc4a856de71f">  | <img alt="Skärmavbild 2023-06-19 kl  12 36 22" src="https://github.com/insightsengineering/teal.slice/assets/6959016/596a4eac-1072-4082-8d3e-27f90e70bbe3">  |

Questions are:
- is it really matter how these filters are printed in the rapport as far are you fine with such filters output?
- If we limit number of printed fields is it okey to keep it in similar format (json)?

@chlebowa @m7pr @chlebowa @kartikeyakirar @donyunardi

**Comment by lcd2yyz** [comment]
The purpose of the reporter is to archive the data processing and analysis result, by ensure reproducibility for the input data and subsequently output. This is achieved with minimal fields/lines in the "before" version. Reporter is not meant to reproduce the state of the shiny app.

The "now" version has overwhelming amount of information. Many of the fields are needed for restoring filter settings or bookmarking, but not relevant for data processing to reproducing analysis results (eg. choices, fixed/locked, id). And json formatting looks too much like  codes, not as "human-readable".

So I would prefer to still keep the current "before" version formatting of the reporter. I think we can apply more simplified formatting (eg. instead "selected value" or "selected range", simply use "selected" for all filter classes), but we should only display the selective fields that's most relevant for reproducible data processing.

For future discussion about saving/sharing filter states and/or app bookmarking, instead of json, we should also consider more concise formatting like yaml for better readability and accessibility.

**Comment by chlebowa** [comment]
"selected" may be misleading: does `selected : 5, 6` mean "5 and 6" or "from 5 to 6"? One cannot know if the selection is a range unless one knows how many unique values there are in the data.

How about something like this?
![image](https://github.com/insightsengineering/teal.slice/assets/114988527/f6fdcc6c-f7d8-4037-9b55-9e65ea40a113)

**Comment by lcd2yyz** [comment]
This will be sufficient set of info. 
But perhaps a bit more layman description will be nicer
```
Dataset name:
Variable name:
Selected values: (categorical separate by comma, range values with long dash)
Include NA values:
Include Inf values:
```

**Comment by gogonzo** [comment]
@lcd2yyz I'm preparing changes and so far it looks like this:

For data.frame
```yaml
- Dataset name: ADSL
  Variable name: AGE
  Selected range: 20 - 69
- Dataset name: ADSL
  Variable name: RACE
  Selected values:
  - ASIAN
  - BLACK OR AFRICAN AMERICAN
  - WHITE
  - AMERICAN INDIAN OR ALASKA NATIVE
  - MULTIPLE
  - NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER
  - OTHER
  - UNKNOWN
- Dataset name: ADSL
  Variable name: LSTALVDT
  Selected range: 2021-02-12 - 2023-03-03
  Include NA values: yes
- Dataset name: ADSL
  Variable name: study_duration_secs
  Selected values: '63113904'
```

For MAE
```yaml
- Dataset name: MAE
  Applied expression: MAE$gender == "female"
- Dataset name: MAE
  Variable name: race
  Selected values:
  - asian
  - black or african american
  - white
  Include NA values: yes
- Dataset name: MAE
  Variable name: Protein
  Experiment: RPPAArray
  Filtering by: Genes
  Selected values:
  - ACVRL1
  - AR-R-V
  - ASNS-R-V
```
